# Generated by Django 3.0.8 on 2020-08-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200828_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='suburb',
        ),
    ]
