# Generated by Django 3.0.8 on 2020-08-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200828_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
