# Generated by Django 3.0.8 on 2020-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200828_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirt_size',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
