# Generated by Django 3.0.8 on 2020-08-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='given_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
